os: linux

language: go

go:
  - 1.14.x

services:
  - postgresql
  - docker

env:
  - APP_DB_USERNAME=postgres
  - APP_DB_PASSWORD=
  - APP_DB_NAME=postgres

script:
  # Test the code
  - go test -v ./...
  # Build the code
  - CGO_ENABLED=0 GOARCH=amd64 go build -v -o go-mux-api